# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:8.9.1

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - cd code/web
          - npm install
          - npm run cli
          - cd ../api
          - curl -o meteor_install_script.sh https://install.meteor.com/
          - chmod +x meteor_install_script.sh
          - ./meteor_install_script.sh
          - export PATH=$PATH:~/.meteor/
          - METEOR_ALLOW_SUPERUSER=true meteor --version
          #- METEOR_ALLOW_SUPERUSER=true meteor npm run cli
